name: "CD: Main Workflow"
run-name: ${{ github.actor }} Deployment Workflow

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}
  GITHUB_REPO: 'NextJS-first-project'
on:
  pull_request:
    types: ['opened', synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Installation
        run: yarn install

      - name: Run Production Deployment
        run: yarn deploy:preview
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}
          GITHUB_REPO: 'NextJS-first-project'
