
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "**.js"
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Installation
        run: yarn install

      - name: Run Linter
        run: yarn lint

      - name: Cypress
        uses: cypress-io/github-action@v6
        with:
          browser: chrome

      - name: Run test
        run: yarn test:e2e
