name: "Linting: Flake8 and Black"
run-name: ${{ github.actor }} CI Workflow
on:
    push:
      branches: ["*"]

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'flake8_py3' 
      
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./src"
          use_pyproject: true
        